name: PlotMe-DefaultGenerator
main: com.worldcretornica.plotme_defaultgenerator.PlotMe_DefaultGenerator
version: '0.14'
author: ZachBora
load: startup
website: http://dev.bukkit.org/server-mods/plotme/
loadbefore: [bPermissions, Multiverse-Core]
description: >
             Handles plot creation