name: PlotMe-DefaultGenerator
main: com.worldcretornica.plotme_defaultgenerator.PlotMe_DefaultGenerator
version: '0.14.3'
author: ZachBora
load: startup
website: http://dev.bukkit.org/server-mods/plotme/
loadbefore: [Multiverse-Core, MultiWorld, PlotMe-Core]
description: >
             Handles plot creation